/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DTO.NhanVien;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmFunction extends javax.swing.JFrame {

    private int access;
    private String manv;

    /**
     * Creates new form frmFunction
     */
    public frmFunction() {
        initComponents();
        setTitle("Cửa hàng tiện lợi Nhật Long");
        setLocationRelativeTo(new frmLogin());
    }

    public frmFunction(int access){
        this.access = access;
        initComponents();
        setTitle("Cửa hàng tiện lợi Nhật Long");
        setLocationRelativeTo(new frmLogin());
    }
    
    public frmFunction(int access,String manv){
        this.access = access;
        this.manv = manv;
        initComponents();
        setTitle("Cửa hàng tiện lợi Nhật Long");
        setLocationRelativeTo(new frmLogin());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThongTin = new javax.swing.JButton();
        btnLichSu = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnReturnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 494));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThongTin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnThongTin.setText("Thông tin cửa hàng");
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 220, 71));

        btnLichSu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLichSu.setText("Lịch sử bán hàng");
        btnLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLichSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 255, 220, 69));

        btnBanHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBanHang.setText("Bán hàng");
        btnBanHang.setPreferredSize(new java.awt.Dimension(220, 23));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        getContentPane().add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 45, 220, 71));

        btnReturnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReturnLogin.setText("<Trở về đăng nhập>");
        btnReturnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 220, 71));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuActionPerformed
        // TODO add your handling code here:
        frmLichSuBanHang lichSu = new frmLichSuBanHang(access);
        lichSu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLichSuActionPerformed

    private JFrame frame;
    
    private void btnReturnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnLoginActionPerformed
        // TODO add your handling code here:
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Bạn có muốn thoát đăng nhập không?","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
            frmLogin login = new frmLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnReturnLoginActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        // TODO add your handling code here:
        frmThongTin thongtin = new frmThongTin();
        thongtin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(access == 1)
            btnThongTin.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        frmThanhToan thanhToan = new frmThanhToan(manv,access);
        thanhToan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBanHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFunction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnLichSu;
    private javax.swing.JButton btnReturnLogin;
    private javax.swing.JButton btnThongTin;
    // End of variables declaration//GEN-END:variables
}
