/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.table_LoaiHang;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import DAO.table_MatHang;
import DAO.table_NCC;
import DTO.LoaiHang;
import DTO.MatHang;
import DTO.NCC;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class frmHangHoa extends javax.swing.JFrame {
    
    table_MatHang tblMatHang ;
    table_NCC tblNCC;
    table_LoaiHang tblLoai;
    
    DefaultTableModel table;
    
    ArrayList<LoaiHang> arrlh;
    ArrayList<NCC> arrNCC;

    private JFrame frame;
    /**
     * Creates new form frmHangHoa
     */
    public frmHangHoa(){
        
        setTitle("Cửa hàng tiện lợi Nhật Long");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboNCC = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtDVT1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setText("QUẢN LÝ HÀNG HÓA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1480, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Mã hàng:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 240, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Tên hàng:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtTenHang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel3.add(txtTenHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Loại:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtSoLuong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyTyped(evt);
            }
        });
        jPanel3.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Đơn vị tính:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cboLoai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboLoai.setOpaque(false);
        cboLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiActionPerformed(evt);
            }
        });
        jPanel3.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 240, 35));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Số lượng:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        cboNCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboNCC.setOpaque(false);
        jPanel3.add(cboNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 240, 35));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("NCC:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtDVT1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel3.add(txtDVT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 240, -1));

        btnSearch.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 190, 60));

        txtGia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtGia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiaKeyTyped(evt);
            }
        });
        jPanel3.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Giá:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 460));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hàng", "Tên Hàng", "Số lượng", "Đơn vị tính", "Giá", "Loại", "Nhà cung cấp"
            }
        ));
        tblHangHoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblHangHoa.setFillsViewportHeight(true);
        tblHangHoa.setGridColor(new java.awt.Color(0, 0, 153));
        tblHangHoa.setOpaque(false);
        tblHangHoa.setRowHeight(25);
        tblHangHoa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHangHoa);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 450));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 970, 460));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));

        btnExit.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnAdd.setText("CLEAR");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1460, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1480, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Bạn có muốn thoát","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
            frmThongTin thongtin = new frmThongTin();
            thongtin.setVisible(true);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void cboLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tblHangHoa.setRowHeight(10);
        LoadDataHangHoa();
    }//GEN-LAST:event_formWindowOpened

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked
        // TODO add your handling code here:
        table = (DefaultTableModel)tblHangHoa.getModel();
        
        int index = tblHangHoa.getSelectedRow();
        
        Clear();
        
        if(index > -1){
            txtID.setText(table.getValueAt(index, 0).toString());
            txtTenHang.setText(table.getValueAt(index, 1).toString());
            txtSoLuong.setText(table.getValueAt(index, 2).toString());
            txtDVT1.setText(table.getValueAt(index, 3).toString());
            txtGia.setText(table.getValueAt(index, 4).toString());
            
            cboLoai.setSelectedItem(table.getValueAt(index, 5).toString());
            cboNCC.setSelectedItem(table.getValueAt(index, 6).toString());
        }
    }//GEN-LAST:event_tblHangHoaMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
                    
        tblMatHang = new table_MatHang();
        
        try{
            String maLoai = searchMaLoai(cboLoai.getSelectedItem().toString());
            String maNCC = searchMaNCC(cboNCC.getSelectedItem().toString());
            String dk = " maHang = '"+txtID.getText()+"' or tenHang = '"+txtTenHang.getText()+"' or dvt = '"+txtDVT1.getText()+"' or maLoai = '"+maLoai+"' or maNCC = '"+maNCC+"'";
            //Đưa dữ liệu lên table
            table = (DefaultTableModel) tblHangHoa.getModel();
            table.setRowCount(0);
            for(MatHang mh: tblMatHang.searchData(dk)){
                String[] mathang = {mh.getId(),mh.getTenHang(),String.valueOf(mh.getSoLuong()),mh.getDvt(),String.valueOf(mh.getGia()),searchLoai(mh.getMaLoai()),searchNCC(mh.getMaNCC())};
                table.addRow(mathang);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:

        Clear();
        
        LoadDataHangHoa();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:

        Clear();
        if(searchMaHang(txtID.getText().trim()))
        {
            JOptionPane.showMessageDialog(rootPane, "Mã hàng đã tồn tại");
            return;
        }
        else if(txtTenHang.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Tên hàng trống");
            return;
        }
        else if(txtDVT1.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Đơn vị tính trống");
                        return;
        }
        else if(txtSoLuong.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Nhập số lượng hàng");
                        return;
        }
                int soLuong = Integer.valueOf(txtSoLuong.getText());
                int gia = Integer.valueOf(txtGia.getText());
                MatHang mh = new MatHang(txtID.getText(), txtTenHang.getText(), txtDVT1.getText(), searchMaLoai(cboLoai.getSelectedItem().toString()), searchMaNCC(cboNCC.getSelectedItem().toString()), soLuong, gia);
                tblMatHang = new table_MatHang();
        try {
            if(tblMatHang.insertMatHang(mh))
            {
                JOptionPane.showMessageDialog(rootPane, "Add success.");
                LoadDataHangHoa();
                Clear();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
            

        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tblHangHoa.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn mặt hàng để xóa");
            return;
        }
        else{
            frame = new JFrame();
            tblMatHang = new table_MatHang();
            if(JOptionPane.showConfirmDialog(frame, "Bạn có muốn xóa","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try {
                    if(tblMatHang.deletetMatHang(txtID.getText()))
                    {
                        JOptionPane.showMessageDialog(rootPane, "Delete success.");
                        LoadDataHangHoa();
                        Clear();
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(frmHangHoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    private void txtSoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyPressed
        

    }//GEN-LAST:event_txtSoLuongKeyPressed

    private void txtSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyTyped
         // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c) || (c == evt.VK_BACK_SPACE || c == evt.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_txtSoLuongKeyTyped

    private void txtGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaKeyTyped
         // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c) || (c == evt.VK_BACK_SPACE || c == evt.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_txtGiaKeyTyped

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(tblHangHoa.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn mặt hàng để sửa");
            return;
        }
        int soLuong = Integer.valueOf(txtSoLuong.getText());
        int gia = Integer.valueOf(txtGia.getText());
        MatHang mh = new MatHang(txtID.getText(), txtTenHang.getText(), txtDVT1.getText(), searchMaLoai(cboLoai.getSelectedItem().toString()), searchMaNCC(cboNCC.getSelectedItem().toString()), soLuong, gia);
        tblMatHang = new table_MatHang();
        try {
            if(tblMatHang.updateMatHang(mh))
            {
                JOptionPane.showMessageDialog(rootPane, "Update success.");
                LoadDataHangHoa();
                Clear();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmHangHoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

        //Load dữ liệu lên form
    public void LoadDataHangHoa(){
        
        tblMatHang = new table_MatHang();
        tblLoai = new table_LoaiHang();
        tblNCC = new table_NCC();
        
        try{
            
            arrNCC = new ArrayList<NCC>();
            arrlh = new ArrayList<LoaiHang>();
            
            DefaultComboBoxModel<String> dftComboBoxLoai =(DefaultComboBoxModel<String>) cboLoai.getModel();
            dftComboBoxLoai.removeAllElements();
            for(LoaiHang loai: tblLoai.getData())
            {
                arrlh.add(loai);
                cboLoai.addItem(loai.getTenLoai());
            }
            
            DefaultComboBoxModel<String> dftComboBoxNCC =(DefaultComboBoxModel<String>) cboNCC.getModel();
            dftComboBoxNCC.removeAllElements();
            for(NCC n: tblNCC.getData())
            {
                arrNCC.add(n);
                cboNCC.addItem(n.getTenNCC());
            }
            
            //Đưa dữ liệu lên table
            table = (DefaultTableModel) tblHangHoa.getModel();
            tblHangHoa.setRowHeight(50);
            table.setRowCount(0);
            for(MatHang mh: tblMatHang.getData()){
                String[] mathang = {mh.getId(),mh.getTenHang(),String.valueOf(mh.getSoLuong()),mh.getDvt(),String.valueOf(mh.getGia()),searchLoai(mh.getMaLoai()),searchNCC(mh.getMaNCC())};
                table.addRow(mathang);
                System.out.println(mh);
            }
            
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public boolean searchMaHang(String ma){
        
        for(int i = 0; i < tblHangHoa.getRowCount();i++){
            
            if(tblHangHoa.getValueAt(i, 0).equals(ma))
                return true;
        }
        return false;
        
    }
    
    private String searchNCC(String idNCC){
        String nameNCC = "";
        for(NCC n: arrNCC){
            if(idNCC.equals(n.getId()))
                nameNCC = n.getTenNCC();
        }
        return nameNCC;
    }
    
    private String searchLoai(String idLoai){
        String nameLoai = "";
        for(LoaiHang l: arrlh){
            if(idLoai.equals(l.getId()))
                nameLoai = l.getTenLoai();
        }
        return nameLoai;
    }
    
    private String searchMaLoai(String tenLoai){
        String idLoai = "";
        for(LoaiHang l: arrlh){
            if(tenLoai.equals(l.getTenLoai()))
                idLoai = l.getId();
        }
        System.out.println(idLoai);
        return idLoai;
    }
        
    private String searchMaNCC(String tenNcc){
        String idNCC = "";
        for(NCC n: arrNCC){
            if(tenNcc.equals(n.getTenNCC()))
                idNCC = n.getId();
        }
        System.out.println(idNCC);
        return idNCC;
    }
    
    private void Clear(){
        txtTenHang.setText("");
        txtDVT1.setText("");
        txtID.setText("");
        txtSoLuong.setText("");
        txtGia.setText("");
        
        cboNCC.setSelectedIndex(0);
        cboLoai.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmHangHoa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTextField txtDVT1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenHang;
    // End of variables declaration//GEN-END:variables
}
